### ISSUE TITLE
ROI size is hardcoded in observe function

### ISSUE THREAD

**Issue by mrtommyb** [PandoraMission/pandora-sim#9]
This line has a hard coded ROI size of 50x50 pixels.
```
data = data.reshape((self.nROIs, nframes, nr, 50, 50)).sum(axis=2)
```

**Comment by christinahedges** [comment]
Closing this because it's fixed in the new version. You can set the ROI size when you initialize a simulation.

**Comment by LindseyWiser** [comment]
I'm able to set an ROI size in initializing the sim, but when calling sim.observe(), I'm still getting this error at the line Tom indicated above: "ValueError: cannot reshape array of size 838860800 into shape (1,200,1,50,50)".
